language: ko-KR

reviews:
  profile: chill
  high_level_summary: true
  sequence_diagrams: false
  auto_review:
    enabled: true
    base_branches: ["fe/develop"]

  path_instructions:
    - path: "frontend/**/*.{js,jsx,ts,tsx}"
      instructions: |
        team-conventions.mdμ ν”„λ΅ νΈμ—”λ“ κ·μΉ™κ³Ό μ•„λ React μ½”λ“ ν’μ§ κΈ°μ¤€μ„ λ°”νƒ•μΌλ΅ λ¦¬λ·°ν•μ„Έμ”.

        ------------------------------------------------------------
        π”¥ React μ½”λ“ ν’μ§ κΈ°μ¤€
        ------------------------------------------------------------

        1) **μƒνƒ κ΄€λ¦¬ (State)**
        - μƒνƒλ” λ°λ“μ‹ ν•„μ”ν• μµμ†ν•λ§ μ μ§€ν•λ‹¤.
        - κ³„μ‚° κ°€λ¥ν• κ°’μ€ stateλ΅ μ €μ¥ν•μ§€ μ•λ”λ‹¤.
        - λ¶ν•„μ”ν• useState, μ¤‘λ³µ μƒνƒ, μ λ„ κ°€λ¥ν• κ°’ μ €μ¥ μ—¬λ¶€ μ κ²€.

        2) **μ„ μ–Έν• ν¨ν„΄ (Declarative)**
        - λ…λ Ήν• λ΅μ§μ„ μ„ μ–Έν•μΌλ΅ λ°”κΏ€ μ μλ”μ§€ ν‰κ°€ν•λ‹¤.
        - μ΅°κ±΄Β·μ‚¬μ΄λ“μ΄ν™νΈΒ·μ΄λ²¤νΈ νλ¦„μ΄ Reactμ¤λ½κ² ν‘ν„λμ–΄ μλ”μ§€ ν™•μΈν•λ‹¤.

        3) **μ—­ν• κ³Ό μ±…μ„ (SRP)**
        - μ»΄ν¬λ„νΈ/ν•¨μκ°€ μ μ ν• λ‹¨μΌ μ±…μ„μ„ κ°€μ§€κ³  μλ”μ§€ ν™•μΈν•λ‹¤.
        - κ³Όλ„ν• λ΅μ§ ν¬ν•¨ λλ” κ³Όν• λ¶„λ¦¬κ°€ μ—†λ”μ§€ μ κ²€ν•λ‹¤.

        4) **λ°λ³µλλ” ν¨ν„΄ / μ•ν‹°ν¨ν„΄ νƒμ§€**
        - PR μ „μ²΄μ—μ„ λ°λ³µμ μΌλ΅ λ‚νƒ€λ‚λ” λ¬Έμ  ν¨ν„΄μ„ μ‹λ³„ν•λ‹¤.
        - κ°μ„ μ΄ μλ―Έ μμ„ λ•λ§ μ μ•ν•λ©° μ¤λ²„μ—”μ§€λ‹μ–΄λ§μ€ ν”Όν•λ‹¤.

        5) **λ¶ν•„μ”ν• λ λ”λ§ λ°©μ§€ (Rendering Optimization)**
        - κ°’μ΄ λ³€ν•μ§€ μ•λ”λ° λ λ”λ§λλ” μ»΄ν¬λ„νΈκ°€ μλ”μ§€ ν™•μΈν•λ‹¤.
        - λ¶€λ¨ λ λ”λ§μ΄ μμ‹μ—κ² λ¶ν•„μ”ν•κ² μ „νλλ”μ§€ μ κ²€ν•λ‹¤.
        - useMemo / useCallbackμ€ ν•„μ”ν• κ²½μ°μ—λ§ μ‚¬μ©λμ—λ”μ§€ ν™•μΈν•λ‹¤.
        - React.memoλ” μ‹¤μ  μ„±λ¥ μ΄μ μ΄ μλ” κ³³μ—λ§ μ μ©λμ—λ”μ§€ ν‰κ°€ν•λ‹¤.

        6) **Side Effects / useEffect μ±…μ„ λ¶„λ¦¬**
        - useEffectκ°€ λ‹¨μΌ μ±…μ„μ„ κ°€μ§€λ”μ§€ ν™•μΈν•λ‹¤.
        - effect λ‚΄λ¶€ μ΅°κ±΄λ¬Έμ΄ λ³µμ΅ν•μ§€ μ•μ€μ§€ μ κ²€ν•λ‹¤.
        - effect λ‚΄λ¶€μ—μ„ stateλ¥Ό μ—¬λ¬ λ² μ„¤μ •ν•΄ λ¶ν•„μ”ν• λ λ”λ§μ„ μ λ°ν•λ”μ§€ ν™•μΈν•λ‹¤.
        - λ¶ν•„μ”ν• useEffectλ¥Ό νƒμ§€ν•λ‹¤.

        7) **μ»΄ν¬λ„νΈ API μΌκ΄€μ„± (Props / Naming / Events)**
        - props μ΄λ¦„μ΄ μ—­ν• μ„ λ…ν™•ν λ“λ¬λ‚΄λ”μ§€ ν™•μΈν•λ‹¤.
        - boolean propsλ” isX / hasY ν¨ν„΄μ„ λ”°λ¥Έλ‹¤.
        - μ΄λ²¤νΈ ν•Έλ“¤λ¬λ” onClick / onChange ν¨ν„΄μ„ μΌκ΄€μ μΌλ΅ μ‚¬μ©ν•λ‹¤.
        - μ μ‚¬ν• μ»΄ν¬λ„νΈλΌλ¦¬ props κµ¬μ΅°λ¥Ό μΌκ΄€λκ² μ μ§€ν•λ‹¤.

        ------------------------------------------------------------
        π§Ύ μ‘λ‹µ ν•μ‹ κ°€μ΄λ“ (μ¤‘μ”λ„ κΈ°λ° λ¦¬λ·°)
        ------------------------------------------------------------
        λ¦¬λ·° κ²°κ³Όλ” λ‹¤μ ν•μ‹μ„ λ°λ“μ‹ λ”°λ¥Έλ‹¤:

        1) **κ°€μ¥ μ¤‘μ”ν• λ¬Έμ  1κ°€μ§€λ¥Ό μµμ°μ„ μΌλ΅ κ°•μ΅°ν•μ—¬ μ„¤λ…ν•λ‹¤.**
           - μ΄ ν•­λ©μ€ λ¦¬λ·°μ λ§¨ μ•μ—μ„ μµμƒμ„ κ°•μ΅° ν¬λ§·μΌλ΅ μ μ‹ν•λ‹¤.

        2) **μΌλ°μ μΈ κ°μ„  ν¬μΈνΈλ” μµλ€ 5κ°κΉμ§€λ§ μ μ‹ν•λ‹¤.**
           - μ¤‘μ”λ„ κΈ°μ¤€μΌλ΅ μ„ λ³„ν•μ—¬ ν•µμ‹¬μ μΈ κ²ƒλ§ λ‚μ—΄ν•λ‹¤.
           - λ¶ν•„μ”ν• κ°μ„ , μλ―Έ μ—†λ” μ΅°μ–Έμ€ μ μ™Έν•λ‹¤.

        3) λ¦¬λ·°λ” λ‹¤μ μ λ©μΌλ΅ μ‹μ‘ν•λ‹¤:
           "# β¨ λ¦¬μ•΅νΈ μ½”λ“ κµ¬μ΅°Β·μƒνƒΒ·μ—­ν• Β·μ„ μ–Έν• ν¨ν„΄ μ κ²€"

        4) μ•„λ ν•μ‹μ— λ§μ¶° bullet pointλ΅ μ‘μ„±ν•λ‹¤:
           - μµμ°μ„  κ°μ„  ν¬μΈνΈ 1κ°€μ§€ (ν•µμ‹¬ λ¬Έμ )
           - μΌλ° κ°μ„  ν¬μΈνΈ μµλ€ 5κ°€μ§€
           - AS-IS μ½”λ“ μμ‹
           - TO-BE κ°μ„  μμ‹
           - μ¤μ¤λ΅ μ κ²€ν•  μ μλ” μ§λ¬Έ 1κ°

        ------------------------------------------------------------
        π“„ ν€ μ»¨λ²¤μ…(team-conventions.md)λ„ ν•¨κ» λ°μν•μ—¬ λ¦¬λ·°ν•μ„Έμ”.
        ------------------------------------------------------------

knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "frontend/docs/team-conventions.md"
