ALTER TABLE organization_category
    ADD COLUMN created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN deleted_at  TIMESTAMP NULL;

ALTER TABLE organization
    ADD COLUMN deleted_at TIMESTAMP NULL;

ALTER TABLE feedback
    ADD COLUMN deleted_at TIMESTAMP NULL;
