ALTER TABLE organization_category
    ADD COLUMN created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN modified_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN deleted_at  DATETIME NULL;

ALTER TABLE organization
    ADD COLUMN deleted_at DATETIME NULL;

ALTER TABLE feedback
    ADD COLUMN deleted_at DATETIME NULL;
